services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  userservice:
    build: ./docker/user_service
    container_name: userservice
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secretD3b
    restart: always

volumes:
  mysql_data:

